### ISSUE TITLE
Будет ли поддержка локализатора в Linux?

### ISSUE THREAD

**Issue by zolotov88** [AWUTERRUS/Terraria_RU#1]
В Linux в Stem версии после копирования файлов в папку с игрой, игра перестает включаться

**Comment by MicrochipQ** [comment]
Будет

**Comment by PoSayDone** [comment]
Как продвиагается? А то очень поиграть охота на нормальном русском языке

**Comment by MicrochipQ** [comment]
https://github.com/AWUTERRUS/Terraria_RU/releases/tag/1.3.0
